apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: myharbor.apps.211-34-231-93.nip.io/edu/vue_crud_security
        imagePullPolicy: Always
        #image: shclub/edu12-3:v11
        env:
          - name: BACKEND_API_URL
            value: "backend" 
        ports:
        - containerPort: 80
