apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: myharbor.apps.211-34-231-93.nip.io/edu/vue_crud_security
        imagePullPolicy: Always
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "local"
        ports:
        - containerPort: 8080
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: backend
# spec:
#   replicas: 1
#   revisionHistoryLimit: 3
#   selector:
#     matchLabels:
#       app: backend
#   template:
#     metadata:
#       labels:
#         app: backend
#     spec:
#       containers:
#       - name: backend
#         image: ghcr.io/heewon00/springboot_crud_security
#         imagePullPolicy: Always
#         env:
#           - name: SPRING_PROFILES_ACTIVE
#             value: "prd"
#           - name: SPRING_DATASOURCE_USERNAME
#             value: "edu"
#           - name: SPRING_DATASOURCE_PASSWORD
#             #value: "caravan"
#             value: "New1234!"
#           - name: SPRING_DATASOURCE_URL
#             #value: "jdbc:mariadb://helm-db-mariadb.edu31.svc.cluster.local:3306/edu"
#             value: "jdbc:mariadb://my-release-mariadb:3306/edu"  
#         ports:
#         - containerPort: 8080
